[EOBS-1225] Food and fluid empty periods are recorded
openeobs/openeobs pull request #111
Opened 2017-05-15 17:27 UTC by moderatemisbehaviour

# Summary
A new section in the reports entitled "Food and Fluid Period With No Entries" lists food and fluid periods during which no food and fluid observations were performed.

These 'empty' periods are only shown for periods since the period in which the first food and fluid observation was ever performed for a particular spell. Periods before the first food and fluid observation do not count.

Contiguous 'empty' periods are displayed in a single entry, with the displayed _start time_ being the start of the first empty periods and the displayed _end time_ being the end of the last empty period. A string of empty periods is broken by either a period that has observations or the currently active period.

# Implementation
A `get_empty_period` method has been added to the `nh_clinical_patient_observation_food_fluid` model. It takes the previously generated _period dictionaries_ as an input and determines what the empty periods are based on those by looking at the time gaps between them. It creates the entry for the report by taking the end datetime of one 'normal' period and the start datetime of the next 'normal' period chronologically.

2017-05-16 09:42 UTC, moderatemisbehaviour commented on nh_food_and_fluid/views/observation_report_template.xml
> +
@Gimpneek suggested adding column headings for extra clarity, I agree.

2017-05-16 09:42 UTC, technotariat requested changes

2017-05-16 09:42 UTC, Gimpneek commented on nh_food_and_fluid/views/observation_report_template.xml
> +
Let's add some column headings on the table to make things easier to read

2017-05-16 10:31 UTC, technotariat approved these changes

2021-03-11 08:28 UTC, moderatemisbehaviour commented
Closing because I can't find another way to remove it from my _pull requests_ view!

2021-03-11 08:28 UTC, closed without merging